# Generated by Django 5.0.6 on 2025-03-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='operatingAirlince',
            new_name='operatingAirlines',
        ),
    ]
