# Generated by Django 5.0.6 on 2025-03-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0002_rename_operatingairlince_flight_operatingairlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='middleName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
